choco install 7zip.install -y
choco install chromedriver -y
choco install erlang -y
choco install fiddler -y
choco install git.install -y
choco install GoogleChrome -y
choco install MsSqlServer2014Express -y
choco install nodejs.install -y
choco install nunit.install -y
choco install nuget.commandline -y
choco install poshgit -y
choco install rabbitmq -y
choco install ruby -y
choco install sql-server-management-studio -y
choco install visualstudiocode -y